# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages
branches:
  only:
    - master
    - develop
addons:
  apt:
    packages:
      - libglpk-dev
  
matrix:
  include:
    - r: devel
    - r: devel
      before_script:
        - echo "if('ROI.plugin.glpk %in% installed.packages()) remove.packages('ROI.plugin.glpk')" | R BATCH --no-save