# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages
branches:
  only:
  - master
  - develop
  
matrix:
  include:
  - r: devel
    addons:
      apt:
      packages:
        - libglpk-dev
  - r: devel