# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages
branches:
  only:
    - master
    - develop
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libglpk-dev
      - gcc-4.9
      - g++-4.9
  
matrix:
  include:
    - r: devel
    - r: release